FROM quay.io/centos/centos:stream10 AS base

LABEL org.opencontainers.image.source="https://github.com/kush-gupt/flux-ocp-demo"
LABEL org.opencontainers.image.description="GLVis-JS Web Server for Laghos visualization"
LABEL org.opencontainers.image.licenses="BSD-3-Clause"

RUN dnf update -y && dnf install -y \
    git \
    python3 \
    python3-pip \
    nodejs \
    npm \
    curl \
    tar \
    && dnf clean all

# Install git-lfs from GitHub releases (packagecloud has GPG issues with CentOS Stream 10)
RUN curl -sL https://github.com/git-lfs/git-lfs/releases/download/v3.5.1/git-lfs-linux-amd64-v3.5.1.tar.gz | tar xz && \
    cd git-lfs-3.5.1 && \
    ./install.sh && \
    cd .. && rm -rf git-lfs-3.5.1

WORKDIR /opt

RUN git lfs install && \
    git clone --depth 1 https://github.com/GLVis/glvis-js.git && \
    cd glvis-js && \
    git lfs pull

RUN pip3 install --no-cache-dir websockets aiohttp

WORKDIR /opt/glvis-js

COPY glvis-proxy.py /opt/glvis-proxy.py
COPY start-server.sh /opt/start-server.sh

RUN chmod +x /opt/glvis-proxy.py /opt/start-server.sh

RUN useradd -u 1001 -g 0 -d /opt/glvis-js glvis && \
    chown -R 1001:0 /opt/glvis-js /opt/glvis-proxy.py /opt/start-server.sh && \
    chmod -R g=u /opt/glvis-js

USER 1001

EXPOSE 8000 19916

CMD ["/opt/start-server.sh"]
